### ISSUE TITLE
Having trouble batch converting flac files to mp3

### ISSUE THREAD

**Issue by PhilMurwin** [MattMcManis/Axiom#1]
I found your tool while looking for a way to convert flac to mp3 and it works well for converting a single file.  Unfortunately I'm having trouble getting it to work in batch mode to convert ~300 files.  The command window is opening and then closing almost immediately.

Not sure what's going wrong... Here's the scripting it's generating:

`cd "D:\Convert\FLAC" && for %f in (*.flac) do (echo)    && "C:\Applications\Axiom.FFmpeg\ffmpeg\bin\ffmpeg.exe" -y -i "D:\Convert\FLAC\%~f" -vn -sn -acodec copy -map 0:a:0? -map_metadata 0 -id3v2_version 3 -threads 8 "D:\Convert\MP3\%~nf.mp3"`

It looks okay to me.  Any idea what the hangup might be?

**Comment by MattMcManis** [comment]
I generated a batch script for flac to mp3. I'm not sure how it generated that for you.

It looks like it's because of -acodec copy, should be -acodec libmp3lame.

`cd "D:\Convert\FLAC\" && for %f in (*.flac) do (echo) && "C:\Applications\Axiom.FFmpeg\ffmpeg\bin\ffmpeg.exe" -y -i "D:\Convert\FLAC\%~f" -vn -sn -acodec libmp3lame -b:a 320k -ac 2 -joint_stereo 1 -map 0:a:0? -map_metadata 0 -id3v2_version 3 -threads 8 "D:\Convert\MP3\%~nf.mp3"`

Steps:
1. Press the 'Keep FFmpeg window open' Button
2. Press Batch
3. Type flac in extension box
4. Press Input Button, Select flac folder
5. Press Output Button, Select mp3 folder
6. Choose Format mp3
7. Choose Audio 320
8. Press Script

---

I've also updated the program, fixing 2 bugs.
https://github.com/MattMcManis/Axiom/releases/download/v1.0.3.0-alpha/Axiom.zip

**Comment by PhilMurwin** [comment]
Now I'm not sure how it generated that for me.  I just tried it and it generated the same script you've posted.  It still didn't really want to work for me.

I'm on Windows 10 and it doesn't appear to like the cd at the beginning.  I was able to navigate to the correct directory manually and then run the rest of the script (starting with for) and it appears to have worked wonderfully.

It appears that the cd might work with a /d
`cd /d "D:\Convert\FLAC"`

Either way with your tips etc above I've now been able to convert the files I was trying to convert.  Many thanks!

**Comment by MattMcManis** [comment]
It may have to do if Axiom.exe is on C:\ Drive and your Convert folder is on D:\ Drive.

I can change to it always generate `cd` as `cd /d` if that will fix it.

**Comment by PhilMurwin** [comment]
I did a couple quick tests and it looks like the /d works fine regardless if you're changing drive and directory or just the directory while staying on the same drive.

It looks like the /d switch has been around since Windows XP so it seems like a pretty safe change.

Whether you make that change or not you can go ahead and close this issue as far as I'm concerned.  Thanks again. 👍

**Comment by MattMcManis** [comment]
Thanks, I will add it in the next update.
