### ISSUE TITLE
Adding yadif and make settings portable

### ISSUE THREAD

**Issue by BeyondVertical** [MattMcManis/Axiom#11]
Cool tool. Could you add the option to use yadif?
And also, would it be possible to save the settings file in the same folder as the binary? Currently it is saved in the user folder. I am using it on a network path and more than one user would have access to it, so the settings in the same folder as the binary would help me.

**Comment by MattMcManis** [comment]
I will look into yadif. I'm working on a new version of the program and will try to add a portable settings ini file.

**Comment by MattMcManis** [comment]
I've added Yadif Deinterlace under Filters Tab. Let me know if you think there should be any changes.

https://ffmpeg.org/ffmpeg-filters.html#yadif-1

![Deinterlace](https://i.imgur.com/fuS0ZkH.png)


It has the options:
- frame
  - `-vf  yadif=0:-1:0`
- field
  - `-vf yadif=1:-1:0`
- cuda frame
  - `-vf  yadif_cuda=0:-1:0`
- cuda field
  - `-vf yadif_cuda=1:-1:0`

For cuda, you will need a custom built FFmpeg that supports it to use that option. I may end up removing cuda since it does not work out of box.
