### ISSUE TITLE
can't pull Log and LogConsole.xaml file

### ISSUE THREAD

**Issue by licong1991** [MattMcManis/Axiom#16]
hi 
I found source code lack of Log.cs and LogConsole.xaml file, So complie failed.
Do you know the reason?
Thanks~

**Comment by MattMcManis** [comment]
Very strange, those files are in the repository in a folder named `Log`. I'm using [GitHub Desktop](https://desktop.github.com/) and it fails to see and upload that folder because it has that name.

I've moved those files out of the `Log` folder and into the `root` folder.

https://github.com/MattMcManis/Axiom/tree/master/source/Axiom/Axiom

Let me know if it works, thanks.

**Comment by MattMcManis** [comment]
It looks like my `.gitignore` was ignoring Log folders `[Ll]og/`. I may change this in the future.

https://raw.githubusercontent.com/MattMcManis/Axiom/master/.gitignore

**Comment by MattMcManis** [comment]
I fixed a bug in 2 Pass Cut time. Let me know if you find something that doesn't work, thanks.

**Comment by licong1991** [comment]
great job.
it works well.
Thank you very much!
