### ISSUE TITLE
v1.7.8.1-alpha was reported to find a Trojan

### ISSUE THREAD

**Issue by iciness** [MattMcManis/Axiom#37]
![Snipaste_2020-04-10_10-51-19](https://user-images.githubusercontent.com/4505686/78957939-4299dc80-7b19-11ea-83b2-17fc15f5e37f.png)

**Comment by BlakeCochrane** [comment]
https://www.virustotal.com/gui/file/a27332faf4ddae6d59abaab1a961b1662e8fca9ae5b43abad55e227c21bdd2ec/detection

False positive from Windows Defender

**Comment by MattMcManis** [comment]
I'm unsure why this would happen, nothing major has changed in the code since last release. Do you know what it could be?

The exe file does not contain any ads or anything malicious. All source code can be downloaded and compiled with Visual Studio for comparison.

The only online connection the program makes at startup is to the [version file](https://raw.githubusercontent.com/MattMcManis/Axiom/master/.version) here on GitHub, and Auto-Update Check can disabled in the Settings Tab. 

Update Available Check Source
https://github.com/MattMcManis/Axiom/blob/master/source/Axiom/Axiom/MainWindow.xaml.cs#L3898

**Comment by MattMcManis** [comment]
I have released a new version 1.7.9.0.
https://github.com/MattMcManis/Axiom/releases

I read someone fixed the same problem by adding a GUID to the Project's Assembly Information. Even though the program doesn't use a registry GUID, I added it to try. 
https://stackoverflow.com/a/44731840

Axiom.exe
https://www.virustotal.com/gui/file/618d14cd0171b8a88cc36db2e34a03edbb740c1b07bbc762dc91e2562e216fc1/detection

Axiom.zip
https://www.virustotal.com/gui/url/b24346822adecc663f9d53a5e053857843652bab8f59aa77ff60e7a7f52f02a7/detection

Axiom.FFmpeg.7z
https://www.virustotal.com/gui/url/91111af3e79f3d3087d55657f49dee3764e9ffdccbb5901ce0780b301905343b/detection

**Comment by iciness** [comment]
Thanks
